#include "PluginProcessor.h"
#include "PluginEditor.h"
ReverbRomanticAudioProcessor::ReverbRomanticAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),apvts(*this,nullptr,"PARAMETERS",Parameters::createParameterLayout()){}
void ReverbRomanticAudioProcessor::prepareToPlay(double sr,int bs){engine.prepare({sr,(juce::uint32)bs,2});}
void ReverbRomanticAudioProcessor::releaseResources(){engine.reset();}
bool ReverbRomanticAudioProcessor::isBusesLayoutSupported(const BusesLayout& l) const {auto o=l.getMainOutputChannelSet();return (o==juce::AudioChannelSet::mono()||o==juce::AudioChannelSet::stereo())&&o==l.getMainInputChannelSet();}
double ReverbRomanticAudioProcessor::getTailLengthSeconds() const {return apvts.getRawParameterValue(Parameters::IDs::decay)->load();}
void ReverbRomanticAudioProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer&){juce::ScopedNoDenormals n;if(b.getNumChannels()==0)return;auto* l=b.getWritePointer(0);auto* r=b.getNumChannels()>1?b.getWritePointer(1):l;if(apvts.getRawParameterValue(Parameters::IDs::bypass)->load()>.5f)return;float mix=apvts.getRawParameterValue(Parameters::IDs::mix)->load()*.01f;float out=juce::Decibels::decibelsToGain(apvts.getRawParameterValue(Parameters::IDs::output)->load());engine.setParameters(apvts.getRawParameterValue(Parameters::IDs::decay)->load()*apvts.getRawParameterValue(Parameters::IDs::time)->load(),apvts.getRawParameterValue(Parameters::IDs::size)->load(),apvts.getRawParameterValue(Parameters::IDs::highCut)->load(),apvts.getRawParameterValue(Parameters::IDs::diffusion)->load(),apvts.getRawParameterValue(Parameters::IDs::density)->load(),apvts.getRawParameterValue(Parameters::IDs::modulation)->load(),apvts.getRawParameterValue(Parameters::IDs::freeze)->load()>.5f);for(int i=0;i<b.getNumSamples();++i){float dl=l[i],dr=r[i],wl=0,wr=0;engine.processStereo(dl,dr,wl,wr);l[i]=(dl*(1-mix)+wl*mix)*out;r[i]=(dr*(1-mix)+wr*mix)*out;}peakL.store(b.getMagnitude(0,0,b.getNumSamples()));peakR.store(b.getMagnitude(juce::jmin(1,b.getNumChannels()-1),0,b.getNumSamples()));}
juce::AudioProcessorEditor* ReverbRomanticAudioProcessor::createEditor(){return new ReverbRomanticAudioProcessorEditor(*this);}void ReverbRomanticAudioProcessor::getStateInformation(juce::MemoryBlock& m){auto x=apvts.copyState().createXml();copyXmlToBinary(*x,m);}void ReverbRomanticAudioProcessor::setStateInformation(const void* d,int s){auto x=getXmlFromBinary(d,s);if(x&&x->hasTagName(apvts.state.getType()))apvts.replaceState(juce::ValueTree::fromXml(*x));}juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new ReverbRomanticAudioProcessor();}
